org: faiz312
app: nest-product-api
service: nest-product-api


plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x


functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
